events {}

http {
    server {
        listen 80;

        # AUTH SERVICE
        location /auth/ {
            rewrite ^/auth/(.*)$ /$1 break;
            proxy_pass http://auth-service:5001;
        }

        # PREDICTION SERVICE
        location /predict {
            proxy_pass http://prediction-service:5002/predict;
        }
    }
}